### ISSUE TITLE
Auto-try reconnection to WiFi network

### ISSUE THREAD

**Issue by sgbaird** [sparks-baird/self-driving-lab-demo#134]

**Comment by sgbaird** [comment]
Just ran into the following:
```python
Traceback (most recent call last):
  File "<stdin>", line 292, in <module>
  File "/lib/umqtt/simple.py", line 214, in check_msg
  File "/lib/umqtt/simple.py", line 201, in wait_msg
  File "<stdin>", line 236, in callback
  File "/lib/umqtt/simple.py", line 133, in publish
OSError: -104
```
Maybe related to connection issues based on https://github.com/micropython/micropython/issues/2055#issuecomment-234270744
