### ISSUE TITLE
MongoDB logging stopped working on the device after some time

### ISSUE THREAD

**Issue by sgbaird** [sparks-baird/self-driving-lab-demo#157]
I noticed that the experiments were running a few seconds faster - because the MongoDB logging stopped on the device side for some reason. The results were still collected by the client but not stored in the database. Resetting the device caused the experiment logging to resume.

The actual errors may be embedded in `results` stored in the Jupyter notebook kernel I'm running. It had been too long to easily check if it was an issue of too many connections or some other resource limitation imposed by MongoDB. It seems more likely to have been recurring ENOMEM errors on the Pico W (i.e., too much RAM being used).

**Comment by sgbaird** [comment]
Possibly related, from error.txt
```python
Traceback (most recent call last):
  File "main.py", line 274, in <module>
  File "/lib/umqtt/simple.py", line 71, in connect
OSError: [Errno 12] ENOMEM
```

**Comment by sgbaird** [comment]
Using `requests` library to do MongoDB logging inside of an MQTT loop may be a bit much for the Pico W microcontroller. Only logging data to an SD card and via the client is worth considering (i.e., dropping the device-side logging to MongoDB) https://github.com/sparks-baird/self-driving-lab-demo/issues/154. I am pushing the limits of the Pico W RAM.
