### ISSUE TITLE
RTD build failing, LaTeX out of memory

### ISSUE THREAD

**Issue by sgbaird** [sparks-baird/self-driving-lab-demo#206]
- https://github.com/noaa-oar-arl/monet/issues/126
- https://github.com/readthedocs/readthedocs.org/pull/9967

> Build output directory for format "pdf" contains multiple files and it is not currently supported. Please, remove all the files but the "pdf" you want to upload.
> ...
> ! TeX capacity exceeded, sorry [main memory size=5000000].
> \par ...@m \@noitemerr {\@@par }\fi \else {\@@par 
>                                                  }\fi 
> l.9255 ...p: Running optimization trial 21{\ldots}
>                                                   
> !  ==> Fatal error occurred, no output PDF file produced!
>
> Transcript written on self-driving-lab-demo.log.
> Latexmk: Index file 'self-driving-lab-demo.idx' was written
> Failure to make 'self-driving-lab-demo.pdf'
> Latexmk: Errors, in force_mode: so I tried finishing targets
> Collected error summary (may duplicate other messages):
>   pdflatex: Command for 'pdflatex' gave return code 256

[readthedocs.org_api_v2_build_21041788.txt](https://github.com/sparks-baird/self-driving-lab-demo/files/11778415/readthedocs.org_api_v2_build_21041788.txt)

**Comment by sgbaird** [comment]
Got a new error:

> We encountered a problem with a command while building your project. To resolve this error, double check your project configuration and installed dependencies are correct and have not changed recently.

> loading configurations for self-driving-lab-demo 0.8.2.post1.dev49+g8ac3de3 ...

> /home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/nbsphinx/__init__.py:1058: RuntimeWarning: You are using an unsupported version of pandoc (1.19.2.4).
> Your version must be at least (2.14.2) but less than (4.0.0).
> Refer to https://pandoc.org/installing.html.
> Continuing with doubts...
>   nbconvert.utils.pandoc.check_pandoc_version()
> /home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/checkouts/latest/docs/notebooks/4.2-paho-mqtt-colab-sdl-demo-test.nblink:846: ERROR: Duplicate substitution definition name: "image0".
> /home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/checkouts/latest/docs/notebooks/4.2-paho-mqtt-colab-sdl-demo-test.nblink:895: ERROR: Duplicate substitution definition name: "image0".
> /home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/checkouts/latest/docs/notebooks/4.2-paho-mqtt-colab-sdl-demo-test.nblink:930: ERROR: Duplicate substitution definition name: "image0".
> /home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/checkouts/latest/docs/notebooks/4.2-paho-mqtt-colab-sdl-demo-test.nblink:965: ERROR: Duplicate substitution definition name: "image0".
> /home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/checkouts/latest/docs/notebooks/4.2-paho-mqtt-colab-sdl-demo-test.nblink:1039: ERROR: Duplicate substitution definition name: "image0".
> looking for now-outdated files... none found
> pickling environment... done
> checking consistency... /home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/checkouts/latest/docs/notebooks/test.nblink: WARNING: document isn't included in any toctree
> done
> processing user_guide.tex... index readme tutorials notebooks/4.2-paho-mqtt-colab-sdl-demo-test notebooks/escience/1.0-traditional-doe-vs-bayesian notebooks/6.1-multi-objective notebooks/6.2.1-multi-fidelity-continuous notebooks/6.2.2-multi-fidelity-discrete notebooks/escience/2.7.1-multi_task notebooks/6.3-batch-optimization notebooks/escience/2.8.2-ax_service_existing_data_saasbo_multi_objective notebooks/escience/2.11-predefined-candidates notebooks/7.3-benchmark-dataset-generation contributing license authors changelog api/modules api/self_driving_lab_demo api/self_driving_lab_demo.data api/self_driving_lab_demo.demos api/self_driving_lab_demo.utils 
> resolving references...
> failed
> 
> Traceback (most recent call last):
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/cmd/build.py", line 285, in build_main
>     app.build(args.force_all, args.filenames)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 353, in build
>     self.builder.build_update()
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 308, in build_update
>     self.build(['__all__'], to_build)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 378, in build
>     self.write(docnames, list(updated_docnames), method)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/builders/latex/__init__.py", line 287, in write
>     doctree = self.assemble_doctree(
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/builders/latex/__init__.py", line 353, in assemble_doctree
>     self.env.resolve_references(largetree, indexfile, self)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 656, in resolve_references
>     self.apply_post_transforms(doctree, fromdocname)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 668, in apply_post_transforms
>     transformer.apply_transforms()
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 79, in apply_transforms
>     super().apply_transforms()
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
>     transform.apply(**kwargs)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/transforms/post_transforms/__init__.py", line 37, in apply
>     self.run(**kwargs)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/builders/latex/transforms.py", line 364, in run
>     self.document.walkabout(visitor)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/docutils/nodes.py", line 199, in walkabout
>     if child.walkabout(visitor):
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/docutils/nodes.py", line 199, in walkabout
>     if child.walkabout(visitor):
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/docutils/nodes.py", line 199, in walkabout
>     if child.walkabout(visitor):
>   [Previous line repeated 5 more times]
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/docutils/nodes.py", line 212, in walkabout
>     visitor.dispatch_departure(self)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/docutils/nodes.py", line 2046, in dispatch_departure
>     return method(node)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/builders/latex/transforms.py", line 434, in depart_table
>     tbody = next(node.findall(nodes.tbody))
> StopIteration
> 
> Exception occurred:
>   File "/home/docs/checkouts/readthedocs.org/user_builds/self-driving-lab-demo/envs/latest/lib/python3.8/site-packages/sphinx/builders/latex/transforms.py", line 434, in depart_table
>     tbody = next(node.findall(nodes.tbody))
> StopIteration
> The full traceback has been saved in /tmp/sphinx-err-frecixsf.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

Related:
- https://github.com/readthedocs/readthedocs.org/issues/7503
- https://github.com/readthedocs/readthedocs.org/issues?q=is%3Aissue+sort%3Aupdated-desc+resolving+references+failed+is%3Aclosed
- https://github.com/readthedocs/readthedocs.org/issues/10132
- https://github.com/sphinx-doc/sphinx/issues/11273

**Comment by sgbaird** [comment]
Fixed by updating to latest readthedocs configuration file format
